portfolio/app/urls.py
from django.urls import path
from . import views

app_name="app"
urlpatterns = [
    path('',views.index, name='index'),
    path('contact', views.contact, name='contact'),
    path('appointment', views.appointment, name='appointment'),
    ]

portfolio/app2/urls.py
from django.urls import path
from . import views
from .views import *


app_name="dashboard"
urlpatterns = [
    path('', views.index, name='index'),

    # path('signin/', views.signin, name='signin'),

    path('add/about',views.add_edit_About, name='add_About'),

    path('add/personalDetails',views.PersonalDetails, name='add_PersonalDetails'),

    path('add/service',views.add_edit_Service, name='add_Service'),
    path('edit/service/<int:id>/',views.add_edit_Service, name='edit_Service'),
    path('service/', ServiceListView.as_view(), name='Service'),
    path('service-delete/<int:id>/', ServiceDeleteView.as_view(), name='deleteService'),

    path('add/testimonial',views.add_edit_Testimonial, name='add_Testimonial'),
    path('edit/testimonial/<int:id>/',views.add_edit_Testimonial, name='edit_Testimonial'),
    path('testimonial/', TestimonialListView.as_view(), name='Testimonial'),
    path('testimonial-delete/<int:id>/', TestimonialDeleteView.as_view(), name='deleteTestimonial'),

    path('edit/contact/<int:id>/',views.add_edit_Contact, name='edit_Contact'),
    path('contact/', ContactListView.as_view(), name='Contact'),
    path('contact-delete/<int:id>/', ContactDeleteView.as_view(), name='deleteContact'),

    path('edit/appointment/<int:id>/',views.add_edit_Appointment, name='edit_Appointment'),
    path('appointment/', AppointmentListView.as_view(), name='Appointment'),
    path('appointment-delete/<int:id>/', AppointmentDeleteView.as_view(), name='deleteAppointment'),

    path('add/album',views.create_or_edit_album, name='add_Album'),
    path('editalbum/<int:album_id>/',views.create_or_edit_album, name='edit_Album'),
    path('album/', AlbumListView.as_view(), name='Album'),
    path('album-delete/<int:id>/', AlbumDeleteView.as_view(), name='deleteAlbum'),

    path('add/companydescription',views.add_edit_CompanyDescription, name='add_CompanyDescription'),
    path('edit/companydescription/<int:id>/',views.add_edit_CompanyDescription, name='edit_CompanyDescription'),
    path('companydescription/', CompanyDescriptionListView.as_view(), name='CompanyDescription'),
    path('companydescription-delete/<int:id>/', CompanyDescriptionDeleteView.as_view(), name='deleteCompanyDescription'),

    path('add/herobanner',views.HeroBanners, name='add_HeroBanner'),
]

portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('dashboard/', include('app2.urls')),
    path('login/', include('useraccount.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/app2/models.py
from django.db import models

# Create your models here.

portfolio/app2/forms.py
from django import forms
from app .models import *


class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = '__all__'


    

class AboutForm(forms.ModelForm):
    class Meta:
        model = About
        fields = '__all__'

class PersonalDetailForm(forms.ModelForm):
    class Meta:
        model = PersonalDetail
        fields = '__all__'

class TestimonialForm(forms.ModelForm):
    class Meta:
        model = Testimonial
        fields = '__all__'


class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = '__all__'


class GalleryForm(forms.ModelForm):
    class Meta:
        model = Gallery
        fields = '__all__'

class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = '__all__'


class CompanyDescriptionForm(forms.ModelForm):
    class Meta:
        model = CompanyDescription
        fields = '__all__'

class HerobannerForm(forms.ModelForm):
    class Meta:
        model = Herobanner
        fields = '__all__'

portfolio/app2/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import *
from django.views.generic.base import View
from .forms import *
from django.contrib import auth
from django.contrib import messages
from django.forms import inlineformset_factory
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from useraccount.decorators import login_required
# Create your views here.

@login_required
def index(request):
    return render(request, 'app2/index.html')


@login_required
def add_edit_About(request):
    instance = None
    try:
        if id:
            instance = About.objects.first()
    except Exception as e:
        messages.warning(request, 'An error occurred while retrieving the About.')
        return redirect('dashboard:add_About')
    if request.method == 'POST':
        form = AboutForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            if instance:  # Edit operation
                messages.success(request, 'About edited successfully.')
                return redirect('dashboard:add_About')  # Redirect to the added About's details page
            else:  # Add operation
                messages.success(request, 'About added successfully.')
                return redirect('dashboard:add_About')  # Redirect to the page for adding new Abouts
        else:
            messages.warning(request, 'Form is not valid. Please correct the errors.')
    else:
        form = AboutForm(instance=instance)
    context = {'form': form, 'instance': instance}
    return render(request, 'app2/create_about.html', context)



def PersonalDetails(request):
    instance = None
    try:
        if id:
            instance = PersonalDetail.objects.first()
    except Exception as e:
        messages.warning(request, 'An error occurred while retrieving the PersonalDetail.')
        return redirect('dashboard:add_PersonalDetails')
    if request.method == 'POST':
        form = PersonalDetailForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            if instance:  # Edit operation
                messages.success(request, 'PersonalDetail edited successfully.')
                return redirect('dashboard:add_PersonalDetails')  # Redirect to the edited PersonalDetail's details page
            else:  # Add operation
                messages.success(request, 'PersonalDetail added successfully.')
                return redirect('dashboard:add_PersonalDetails')  # Redirect to the page for adding new PersonalDetail
        else:
            messages.warning(request, 'Form is not valid. Please correct the errors.')
    else:
        form = PersonalDetailForm(instance=instance)
    context = {'form': form, 'instance': instance}
    return render(request, 'app2/create_PersonalDetails.html', context)

@login_required 
def add_edit_Service(request, id=None):
    instance = None
    try:
        if id:
            instance = Service.objects.get(pk=id)
    except Exception as e:
        messages.warning(request, 'An error occurred while retrieving the Service.')
        return redirect('dashboard:add_Service')
    if request.method == 'POST':
        form = ServiceForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            if instance:  # Edit operation
                messages.success(request, 'Service edited successfully.')
                return redirect('dashboard:edit_Service', id=instance.id)  # Redirect to the edited Service's details page
            else:  # Add operation
                messages.success(request, 'Service added successfully.')
                return redirect('dashboard:add_Service')  # Redirect to the page for adding new Services
        else:
            messages.warning(request, 'Form is not valid. Please correct the errors.')
    else:
        form = ServiceForm(instance=instance)
    context = {'form': form, 'instance': instance}
    return render(request, 'app2/create_Service.html', context)

class ServiceListView(View):
    template_name = 'app2/Service.html'
    def get(self, request):
        prod = Service.objects.all()
   
        return render(request, self.template_name, {'details': prod})

class ServiceDeleteView(View):
    template_name = 'app2/Service.html'
    def get(self, request, id):
        record = get_object_or_404(Service, id=id)
        return render(request, self.template_name, {'details': record})
    def post(self, request, id):
        record = get_object_or_404(Service, id=id)
        record.delete()
        return redirect('dashboard:Service')



@login_required 
def add_edit_Contact(request, id=None):
    instance = None
    try:
        if id:
            instance = Contact.objects.get(pk=id)
    except Exception as e:
        messages.warning(request, 'An error occurred while retrieving the Contact.')
        return redirect('dashboard:add_Contact')
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            if instance:  # Edit operation
                messages.success(request, 'Contact edited successfully.')
                return redirect('dashboard:edit_Contact', id=instance.id)  # Redirect to the edited Contact's details page
            else:  # Add operation
                messages.success(request, 'Contact added successfully.')
                return redirect('dashboard:add_Contact')  # Redirect to the page for adding new Contacts
        else:
            messages.warning(request, 'Form is not valid. Please correct the errors.')
    else:
        form = ContactForm(instance=instance)
    context = {'form': form, 'instance': instance}
    return render(request, 'app2/create_Contact.html', context)

class ContactListView(View):
    template_name = 'app2/Contact.html'
    def get(self, request):
        prod = Contact.objects.all()
   
        return render(request, self.template_name, {'details': prod})

class ContactDeleteView(View):
    template_name = 'app2/Contact.html'
    def get(self, request, id):
        record = get_object_or_404(Contact, id=id)
        return render(request, self.template_name, {'details': record})
    def post(self, request, id):
        record = get_object_or_404(Contact, id=id)
        record.delete()
        return redirect('dashboard:Contact')


@login_required 
def add_edit_Testimonial(request, id=None):
    instance = None
    try:
        if id:
            instance = Testimonial.objects.get(pk=id)
    except Exception as e:
        messages.warning(request, 'An error occurred while retrieving the Testimonial.')
        return redirect('dashboard:add_Testimonial')
    if request.method == 'POST':
        form = TestimonialForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            if instance:  # Edit operation
                messages.success(request, 'Testimonial edited successfully.')
                return redirect('dashboard:edit_Testimonial', id=instance.id)  # Redirect to the edited Testimonial's details page
            else:  # Add operation
                messages.success(request, 'Testimonial added successfully.')
                return redirect('dashboard:add_Testimonial')  # Redirect to the page for adding new Testimonials
        else:
            messages.warning(request, 'Form is not valid. Please correct the errors.')
    else:
        form = TestimonialForm(instance=instance)
    context = {'form': form, 'instance': instance}
    return render(request, 'app2/create_Testimonial.html', context)

class TestimonialListView(View):
    template_name = 'app2/Testimonial.html'
    def get(self, request):
        prod = Testimonial.objects.all()
   
        return render(request, self.template_name, {'details': prod})

class TestimonialDeleteView(View):
    template_name = 'app2/Testimonial.html'
    def get(self, request, id):
        record = get_object_or_404(Testimonial, id=id)
        return render(request, self.template_name, {'details': record})
    def post(self, request, id):
        record = get_object_or_404(Testimonial, id=id)
        record.delete()
        return redirect('dashboard:Testimonial')




@login_required 
def add_edit_Appointment(request, id=None):
    instance = None
    try:
        if id:
            instance = Appointment.objects.get(pk=id)
    except Exception as e:
        messages.warning(request, 'An error occurred while retrieving the Appointment.')
        return redirect('dashboard:add_Appointment')
    if request.method == 'POST':
        form = AppointmentForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            if instance:  # Edit operation
                messages.success(request, 'Appointment edited successfully.')
                return redirect('dashboard:edit_Appointment', id=instance.id)  # Redirect to the edited Appointment's details page
            else:  # Add operation
                messages.success(request, 'Appointment added successfully.')
                return redirect('dashboard:add_Appointment')  # Redirect to the page for adding new Appointments
        else:
            messages.warning(request, 'Form is not valid. Please correct the errors.')
    else:
        form = AppointmentForm(instance=instance)
    context = {'form': form, 'instance': instance}
    return render(request, 'app2/create_Appointment.html', context)

class AppointmentListView(View):
    template_name = 'app2/Appointment.html'
    def get(self, request):
        prod = Appointment.objects.all()
   
        return render(request, self.template_name, {'details': prod})

portfolio/app2/templates/app2/Album.html
{% extends 'app2/base.html' %}
{% load static %}
{% block title %} 
Album
{% endblock %}
{% block body %}
<title>Album</title>

            <!-- ============================================================== -->
            <!-- Start Page Content here -->
            <!-- ============================================================== -->

            <div class="content-page">
                <div class="content">

                    <!-- Start Content-->
                    <div class="container-fluid">
                       
                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">
                                  
                                    <h4 class="page-title">Album</h4>
                                </div>
                            </div>
                        </div>
                        <!-- end page title -->
                     
                        <div class="row">
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-body">
                                        <div class="row mb-2">
                                            <div class="col-sm-4">
                                                <a href="{% url 'dashboard:add_Album' %}" class="btn btn-danger rounded-pill mb-3"><i class="mdi mdi-plus"></i>Add Album</a>
                                            </div>
                                        </div>
                                        

                                        <div class="table-responsive"style="overflow-x: auto; width: 100%;" >
                                            <table class="table table-striped dt-responsive w-100 " id=""  >
                                                    <tr>
                                                        <th>Id</th>
                                                        <th>Title</th>
                                                        <th>Image</th>
                                                        
                                                        <th style="width: 120px;">Action</th>
                                                    </tr>
                                      {%for item in details%}

                                        <tr>
                                                            

                                  
                                            <td>
                                                {{forloop.counter}}
                                            </td>
                                            <td>
                                                {{item.title}}
                                            </td>

                                            <td>
                                                <div class="image-album">
                                                 {% if item.image %}   <img class="thumbnail" src="{{item.image.url}}" alt="Thumbnail Image">{%endif%}
                                                    <!-- Add more thumbnail images here if you have multiple images in the album -->
                                                </div>
                                                <div class="modal" id="imageModal">
                                                    <span class="close-btn" onclick="closeModal()">&times;</span>
                                                    <img class="modal-content" id="modalImage">
                                                </div>
                                            
                                                <script src="script.js"></script>
                                            </td>
                                            
                    
                                   
                                            <td style ="display:inline-block; margin-right:5px;" >
                                                <a href="{% url 'dashboard:edit_Album' item.id %}" class="font-18 text-info" data-bs-toggle="tooltip" data-bs-placement="top" title="Edit"><i class="uil uil-pen"></i></a>
                                                <a href="#AlbumDeleteModel{{item.id}}" class="delete" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
                                            </td>
                                         
                                        </tr>
                                        {%endfor%} 
                                        </tr>
                                                                            
                             </table>                                         
                                        
                                    </div>
                                    <nav>
                                        <ul class="pagination pagination-rounded mb-0">
                                            {% if details.has_previous %}
                                                <li class="page-item"><a href="?page=1" class="page-link">First</a></li>
                                                <li class="page-item"><a href="?page={{ details.previous_page_number }}" class="page-link">Previous</a></li>
                                            {% endif %}

                                            {% for num in details.paginator.page_range %}
                                                {% if details.number == num %}
                                                    <li class="page-item active"><a href="?page={{ num }}" class="page-link">{{ num }}</a></li>
                                                {% else %}
                                                    <li class="page-item"><a href="?page={{ num }}" class="page-link">{{ num }}</a></li>
                                                {% endif %}
                                            {% endfor %}

                                            {% if details.has_next %}
                                                <li class="page-item"><a href="?page={{ details.next_page_number }}" class="page-link">Next</a></li>
                                                <li class="page-item"><a href="?page={{ details.paginator.num_pages }}" class="page-link">Last</a></li>
                                            {% endif %}
                                        </ul>
                                    </nav>
                                    <div class="modal" id="imageModal">
                                        <div class="modal-content">
                                            <img src="" alt="Full Image" class="modal-image" id="modalImage">
                                        </div>
                                    </div>
                                    </div> <!-- end card-body-->
                                </div> <!-- end card-->
                            </div> <!-- end col -->
                        </div>
                        <!-- end row -->
                        
                    </div> <!-- container -->
                

                </div> <!-- content -->
                	<!-- Delete Modal HTML -->
          
   
    {% block content %}
    {% for item in details %}
        <div class="modal fade"  id="AlbumDeleteModel{{item.id}}"  tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content custom-modal">
                        <div class="modal-footer">
                            Are you sure you want to delete this Album Id Number #{{ item.id }}
                          
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                            <form method="post" action="{% url 'dashboard:deleteAlbum' item.id%}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </div>
                    </div>
                </div>
        
                                </div>
                    {% endfor %}
                    <style>
                    /* static/css/custom.css */

                    .custom-modal {
                        background-color: white; /* Set the background color to white */
                    }
                    </style>
                    <!-- Include your other CSS files -->
                    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">

                    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
                    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

                    <script>
                        $(document).ready(function () {
                            $('#AlbumdeleteModal').modal('show');
                        });
                    </script>
                    {% endblock %}
              
{%endblock%}

portfolio/app2/templates/app2/create_CompanyDescription.html
{% extends 'app2/base.html' %}
{% load static %}
{% block title %} 
Company Description
{% endblock %}
{% block body %}
            <!-- Start Page Content here -->

            <div class="content-page">
                <div class="content">

                    <!-- Start Content-->
                    <div class="container-fluid">

                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">
                                    <h4 class="page-title">Company Description</h4>
                                </div>
                            </div>
                        </div>
                        <!-- end page title -->

                        

                        <div class="row">
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-body">
                                        <form method="post" enctype="multipart/form-data" action="{% if instance %}{% url 'dashboard:edit_CompanyDescription'  instance.id %}{% else %}{% url 'dashboard:add_CompanyDescription' %}{% endif %}">
                                            {% csrf_token %}
                                            {{form.media}}
                                            {% if messages %}
                                            {% for msg in messages %}
                                                <div class="alert alert-{{ msg.tags }} alert-dismissible text-bg-{{ msg.tags }} border-0 fade show" role="alert">
                                                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert" aria-label="Close"></button>
                                                    <strong>{% if msg.tags == 'success' %}Success{% elif msg.tags == 'warning' %}Warning{% endif %} - </strong>{{ msg.message }}
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                    <div class="row">
                                        <!-- input -->
                                        <div class="col-xl-6">
                                        <div class="mb-3">
                                            <label class="form-label">Title</label>
                                            <input type="text" name="{{ form.title.name }}" id="{{ form.title.id_for_label }}" class="form-control"
                                            value="{% if instance %}{{ instance.title }}{% endif %}" placeholder="Enter title" required>
                                        </div>

                                        <div class="mb-3">
                                            <label class="form-label">Time</label>
                                            <input type="text" name="{{ form.time.name }}" id="{{ form.time.id_for_label }}" class="form-control"
                                            value="{% if instance %}{{ instance.time }}{% endif %}" placeholder="Enter time" required>
                                        </div>
            
                                        
                                        <div class="mb-3">
                                            <label for="{{ form.icon.id_for_label }}" class="form-label">Icon :</label>
                                            <input type="file" name="{{ form.icon.name }}" id="{{ form.icon.id_for_label }}" class="form-control" {% if not instance %}required{% endif %} onchange="showPreview(this);">
                                            <div id="iconContainer" style="width:auto; height:auto;">
                                                <img class="img-fluid" id="iconPreview" src="{% if instance %}{{ instance.icon.url }}{% endif %}" alt="" >
                                            </div>
                                        </div>
                                        
                                        
                                        <!-- input -->
                                        </div>
                                        <div class="col-xl-6">

                                            <div class="mb-3">
                                                <label class="form-label">Description</label>
                                               {{form.description}}
                                             </div>
                                        </div>
                                          <div class="col-lg-12">
                                             {% if instance %}
                                             <button type="submit" class="btn btn-primary">Update</button>
                                         {% else %}
                                             <button type="submit" class="btn btn-primary">Add</button>
                                         {% endif %}
                                        </div>
                                       </div>
                                       </form>
                        
                    </div> <!-- container -->

                </div> <!-- content -->


      {% endblock %}

portfolio/app2/templates/app2/index.html
{% extends 'app2/base.html' %}
{% load static %}
{% block title %} 
Dashboard
{% endblock %}
{% block body %}
<title>dashboard</title>
            <!-- ============================================================== -->
            <!-- Start Page Content here -->
            <!-- ============================================================== -->

            <div class="content-page">
                <div class="content">

                    <!-- Start Content-->
                    <div class="container-fluid">

                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">                                    
                                    
                                    <h4 class="page-title">Dashboard</h4>
                                </div>
                            </div>
                        </div>
                   
                        
                        <!-- end row-->

                        <body style="display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; font-family: Arial, sans-serif;">
                            <div  class="card"style="text-align: center;">
                                <br><br><br><br><br><br><br><br><br><br><br>
                                <h4 style="margin: 0;">WELCOME TO ADMIN HOMEPAGE</h4><br><br><br><br><br><br><br>
                                <br><br><br><br><br><br><br>
                       
                            </div>
                        </body>
                    
                
                        <!-- end row -->


                    </div>
                    <!-- container -->

                </div>
                <!-- content -->

             {%endblock%}