portfolio/app/urls.py
from django.urls import path
from . import views

app_name="app"
urlpatterns = [
    path('',views.index, name='index'),
    path('contact', views.contact, name='contact'),
    path('appointment', views.appointment, name='appointment'),
    ]

portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('dashboard/', include('app2.urls')),
    path('login/', include('useraccount.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/useraccount/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name="useraccount"
urlpatterns = [
        path('', views.login, name='login'),
        path('userlogout/', views.userlogout, name='userlogout'),
        path('change_password',views.change_password,name='change_password'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/useraccount/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin

class UserManager(BaseUserManager):
    def create_user(self, email, firstname, lastname, phone_No, password=None):
        if not email:
            raise ValueError('User must have an email address')
        user = self.model(
            email=self.normalize_email(email),
            firstname=firstname,
            lastname=lastname,
            phone_No=phone_No
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    def create_superuser(self, email, firstname, lastname, phone_No, password=None):
        user = self.create_user(
            email,
            firstname=firstname,
            lastname=lastname,
            phone_No=phone_No,
            password=password
        )
        user.is_admin = True
        user.is_superuser = True
        user.save(using=self._db)
        return user
        
class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        verbose_name='Email',
        max_length=255,
        unique=True,
    )
    firstname = models.CharField(max_length=200)
    lastname = models.CharField(max_length=200)
    is_admin = models.BooleanField(default=False)
    is_user = models.BooleanField(default=False)
    is_subAdmin = models.BooleanField(default=False)
    phone_No = models.CharField(max_length=150, null=True, blank=True)
    avatar = models.ImageField(upload_to="avatarimage/", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['firstname','lastname', 'phone_No']
    def __str__(self):
        return self.firstname

    @property
    def is_staff(self):
        return self.is_admin or self.is_user

portfolio/useraccount/views.py
from django.shortcuts import render, redirect
# from account.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import auth
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from .decorators import login_required

# Create your views here.
def signin(request):
    return render(request, 'useraccount/sign-in.html')

def login(request):
    try:
        if request.user.is_authenticated:
            return redirect('dashboard:index')
        if request.method == "POST":
            email = request.POST['useremail']
            password = request.POST['password']
            user_obj = authenticate(email=email, password=password)
            if not user_obj:
                messages.warning(request, "Invalid username and password...")
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            # Check the user's role and redirect accordingly
            if user_obj.is_admin:
                auth.login(request, user_obj)
                messages.success(request, "Admin login successful!")
                return redirect('dashboard:index')
            # elif user_obj.is_user:
            #     auth.login(request, user_obj)
            #     messages.success(request, "User login successful!")
            #     return redirect('dashboard:index')
            
            else:
                messages.warning(request, 'Invalid Password')
            return redirect('dashboard:index')
        return render(request, 'useraccount/sign-in.html')
    except Exception as e:
        messages.warning(request, 'Something went wrong...')
        return render(request, 'useraccount/sign-in.html')
        

@login_required
def userlogout(request):
    auth.logout(request)
    messages.info(request,"logout successfully..")
    return redirect('useraccount:login')



@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, 'Your password was successfully updated!')
            return redirect('useraccount:login')
        else:
            messages.error(request,form.errors) 
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'useraccount/change_password.html', {'form': form})

portfolio/useraccount/templates/useraccount/change_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    
<!-- Mirrored from coderthemes.com/hyper/saas/pages-login.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 02 Aug 2023 07:34:27 GMT -->
<head>
        <meta charset="utf-8" />
        <title>Change password</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
        <meta content="Coderthemes" name="author" />

        <!-- App favicon -->
        <link rel="shortcut icon" href="{{personaldetail.favicon.url}}" style="height: 100px;">
        
        <!-- Theme Config Js -->
        <script src="{% static 'useraccount/assets2/js/hyper-config.js' %}"></script>

        <!-- App css -->
        <link href="{% static 'useraccount/assets2/css/app-saas.min.css' %}" rel="stylesheet" type="text/css" id="app-style" />

        <!-- Icons css -->
        <link href="{% static 'useraccount/assets2/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
    </head>
    
    <body class="authentication-bg position-relative">
        <div class="position-absolute start-0 end-0 start-0 bottom-0 w-100 h-100">
            <svg xmlns='http://www.w3.org/2000/svg' width='100%' height='100%' viewBox='0 0 800 800'>
                <g fill-opacity='0.22'>
                    <circle style="fill: rgba(var(--ct-primary-rgb), 0.1);" cx='400' cy='400' r='600'/>
                    <circle style="fill: rgba(var(--ct-primary-rgb), 0.2);" cx='400' cy='400' r='500'/>
                    <circle style="fill: rgba(var(--ct-primary-rgb), 0.3);" cx='400' cy='400' r='300'/>
                    <circle style="fill: rgba(var(--ct-primary-rgb), 0.4);" cx='400' cy='400' r='200'/>
                    <circle style="fill: rgba(var(--ct-primary-rgb), 0.5);" cx='400' cy='400' r='100'/>
                </g>
            </svg>
        </div>
        <div class="account-pages pt-2 pt-sm-5 pb-4 pb-sm-5 position-relative">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xxl-4 col-lg-5">
                        <div class="card">

                            <!-- Logo -->
                            <div class="card-header py-4 text-center bg-primary" style="background-color: #0077b6;">
                                <a href="/">
                                    <img src="{{personaldetail.logo.url}}" alt="logo" height="60" width="100">
                                </a>
                            </div>

                            <div class="card-body p-4">
                                
                                <div class="text-center w-75 m-auto">
                                    <h4 class="text-dark-50 text-center pb-0 fw-bold">Change password</h4>
                                </div>

                                <form  method="post" action="{% url 'useraccount:change_password' %}">
                                   {{form.errors}}
                                    {% csrf_token %}
                                    {% comment %} {{form.as_p}} {% endcomment %}
                                    {% comment %} {{form.as_p}} {% endcomment %}
                                    <div class="mb-3">
                                        <label for="email" class="form-label">Old password</label>
                                        <input class="form-control" type="password" name="old_password" id="id_old_password" required="" placeholder="Enter old password">
                                    </div>

                                    <div class="mb-3">
                                        <label for="password" class="form-label">New Password</label>
                                        <div class="input-group input-group-merge">
                                            <input type="password" name="new_password1" id="id_new_password1" class="form-control" placeholder="Enter new password">
                                            <div class="input-group-text" data-password="false">
                                                <span class="password-eye"></span>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="mb-3">
                                        <label for="password" class="form-label">Re-enter Password</label>
                                        <div class="input-group input-group-merge">
                                            <input type="password" name="new_password2" id="id_new_password2" class="form-control" placeholder="Re-enter new password">
                                            <div class="input-group-text" data-password="false">
                                                <span class="password-eye"></span>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="mb-3 mb-3">
                                        <div class="form-check">
                                            <input type="checkbox" class="form-check-input" id="checkbox-signin" checked>
                                            <label class="form-check-label" for="checkbox-signin">Remember me</label>
                                        </div>
                                    </div>

                                    <div class="mb-3 mb-0 text-center">
                                        <button class="btn btn-primary" type="submit"> Change password </button>
                                    </div>

                                </form>
                            </div> <!-- end card-body -->
                        </div>
                        <!-- end card -->

                        {% comment %} <div class="row mt-3">
                            <div class="col-12 text-center">
                                <p class="text-muted">Don't have an account? <a href="pages-register.html" class="text-muted ms-1"><b>Sign Up</b></a></p>
                            </div> <!-- end col -->
                        </div> {% endcomment %}
                        <!-- end row -->

                    </div> <!-- end col -->
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end page -->

        <footer class="footer footer-alt">
            2024 - <script>document.write(new Date().getFullYear())</script>Copyright &copy;  All rights reserved.
        </footer>
        <!-- Vendor js -->
        <script src="{% static 'useraccount/assets2/js/vendor.min.js' %}"></script>
        
        <!-- App js -->
        <script src="{% static 'useraccount/assets2/js/app.min.js' %}"></script>

    </body>

<!-- Mirrored from coderthemes.com/hyper/saas/pages-login.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 02 Aug 2023 07:34:27 GMT -->
</html>

portfolio/useraccount/templates/useraccount/sign-in.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    
<!-- Mirrored from coderthemes.com/hyper/saas/pages-login.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 02 Aug 2023 07:34:27 GMT -->
<head>
        <meta charset="utf-8" />
        <title>Log In</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
        <meta content="Coderthemes" name="author" />

        <!-- App favicon -->
        <link rel="shortcut icon" href="{{personaldetail.favicon.url}}" style="height: 100px;">
        
        <!-- Theme Config Js -->
        <script src="{% static 'useraccount/assets2/js/hyper-config.js' %}"></script>

        <!-- App css -->
        <link href="{% static 'useraccount/assets2/css/app-saas.min.css' %}" rel="stylesheet" type="text/css" id="app-style" />

        <!-- Icons css -->
        <link href="{% static 'useraccount/assets2/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
    </head>
    
    <body class="authentication-bg position-relative">
        <div class="position-absolute start-0 end-0 start-0 bottom-0 w-100 h-100">
            <svg xmlns='http://www.w3.org/2000/svg' width='100%' height='100%' viewBox='0 0 800 800'>
                <g fill-opacity='0.22'>
                    <circle style="fill: rgba(var(--ct-primary-rgb), 0.1);" cx='400' cy='400' r='600'/>
                    <circle style="fill: rgba(var(--ct-primary-rgb), 0.2);" cx='400' cy='400' r='500'/>
                    <circle style="fill: rgba(var(--ct-primary-rgb), 0.3);" cx='400' cy='400' r='300'/>
                    <circle style="fill: rgba(var(--ct-primary-rgb), 0.4);" cx='400' cy='400' r='200'/>
                    <circle style="fill: rgba(var(--ct-primary-rgb), 0.5);" cx='400' cy='400' r='100'/>
                </g>
            </svg>
        </div>
        <div class="account-pages pt-2 pt-sm-5 pb-4 pb-sm-5 position-relative">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xxl-4 col-lg-5">
                        <div class="card">

                            <!-- Logo -->
                            <div class="card-header py-4 text-center bg-primary" style="background-color: black;">
                                <a href="/">
                                    <img src="{{personaldetail.logo.url}}" alt="logo" height="60" width="100">
                                </a>
                            </div>

                            <div class="card-body p-4">
                                
                                <div class="text-center w-75 m-auto">
                                    <h4 class="text-dark-50 text-center pb-0 fw-bold">Sign In</h4>
                                    <p class="text-muted mb-4">Enter your email address and password to access admin panel.</p>
                                </div>

                                <form  method="post" action="{% url 'useraccount:login' %}">
                                    {% csrf_token %}
                                    <div class="mb-3">
                                        <label for="email" class="form-label">Email address</label>
                                        <input class="form-control" type="email" name="useremail" id="email" required="" placeholder="Enter your email">
                                    </div>

                                    <div class="mb-3">
                                        {% comment %} <a href="{% url 'useraccount:change_password' %}" class="text-muted float-end"><small>Forgot your password?</small></a> {% endcomment %}
                                        <label for="password" class="form-label">Password</label>
                                        <div class="input-group input-group-merge">
                                            <input type="password" name="password" id="password" class="form-control" placeholder="Enter your password">
                                            <div class="input-group-text" data-password="false">
                                                <span class="password-eye"></span>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="mb-3 mb-3">
                                        <div class="form-check">
                                            <input type="checkbox" class="form-check-input" id="checkbox-signin" checked>
                                            <label class="form-check-label" for="checkbox-signin">Remember me</label>
                                        </div>
                                    </div>

                                    <div class="mb-3 mb-0 text-center">
                                        <button class="btn btn-primary" type="submit"> Log In </button>
                                    </div>

                                </form>
                            </div> <!-- end card-body -->
                        </div>
                        <!-- end card -->

                        {% comment %} <div class="row mt-3">
                            <div class="col-12 text-center">
                                <p class="text-muted">Don't have an account? <a href="pages-register.html" class="text-muted ms-1"><b>Sign Up</b></a></p>
                            </div> <!-- end col -->
                        </div> {% endcomment %}
                        <!-- end row -->

                    </div> <!-- end col -->
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end page -->

        <footer class="footer footer-alt">
            2018 - <script>document.write(new Date().getFullYear())</script>Copyright &copy;  All rights reserved.
        </footer>
        <!-- Vendor js -->
        <script src="{% static 'useraccount/assets2/js/vendor.min.js' %}"></script>
        
        <!-- App js -->
        <script src="{% static 'useraccount/assets2/js/app.min.js' %}"></script>

    </body>

<!-- Mirrored from coderthemes.com/hyper/saas/pages-login.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 02 Aug 2023 07:34:27 GMT -->
</html>